language: python
python:
  - "3.7"
env:
  - DJANGO=3.0.4
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - python manage.py check
  - python manage.py makemigrations
  - python manage.py migrate
#  - mysql -e 'create database test;' -u root

# command to run tests
script:
  - python manage.py test
  - coverage run --source=accounts,base,registration,blog manage.py test
  
after_success:
  - coveralls
